global:
  checkNewVersion: true
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true

entryPoints:
  # Redirect HTTP to HTTPS
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  # HTTPS endpoint with wildcard domain
  https:
    address: ":443"
    http:
      tls:
        # Generate a wildcard domain certificate
        certResolver: supareelcfchallenge
        domains:
          - main: supareel.com
            sans:
              - "*.supareel.com"
      middlewares:
        - securityHeaders@file

providers:
  providersThrottleDuration: 2s

  # File provider for middleware and other configurations
  file:
    filename: /fileConfig.yml
    watch: true

  # Docker provider for services running inside Docker
  docker:
    watch: true
    network: supareel_net # Ensure this matches your Docker network name
    swarmModeRefreshSeconds: 15s # Comment out or remove if using Traefik v3
    exposedByDefault: false

# Enable Traefik UI
api:
  dashboard: true
  insecure: true

# Log level: INFO|DEBUG|ERROR
log:
  level: INFO

# Use Let's Encrypt to generate SSL certificates
certificatesResolvers:
  supareelcfchallenge:
    acme:
      email: 19mandal97@gmail.com
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
